### ISSUE TITLE
TImeseries data?

### ISSUE THREAD

**Issue by JohnnySheffield** [ClimbsRocks/machineJS#148]
This repo looks uber crazy. Still just trying to wrap my head around it.

I was thinking to start playing with giving it some time-series data in csv.

Are there some thingies i should watch out if i would like to see some meaningful output?

**Comment by ClimbsRocks** [comment]
It should work well with timeseries data! 

I even started building out some automated feature engineering for dates: 
https://github.com/ClimbsRocks/data-formatter/blob/master/helperFunctions/featureEngineering.py

That particular feature was not a primary focus, so hasn't been thoroughly tested yet. But regardless, this project should work well with timeseries data! 

Let me know what issues you encounter.

**Comment by ClimbsRocks** [comment]
Hey @JohnnySheffield! Closing this issue for now, but I'd love to hear about your experiences using this project. I'm actually working on it today while on the plane, so if you've got any feedback or questions right now, I'm available :)
